### ISSUE TITLE
Can I use your code for Commercial Purpose?

### ISSUE THREAD

**Issue by shrikantjadhav5589** [tmyroadctfig/twaindotnet#29]
Thanks @sivaktamilan. I gone through your article of Scanning. Everything is work perfect till now. Can I use your code for Commercial Purpose?

**Comment by sivaktamilan** [comment]
Hi, It's not me. Have a look at the contributors of the <b>twaindotnet</b> project here https://github.com/tmyroadctfig/twaindotnet/graphs/contributors
And you can read the license terms in the  License.txt file.

**Comment by shrikantjadhav5589** [comment]
Hello sir,
Thank u for ur reply. I will go through it.

Thank you,

Regards,
Shrikant Jadhav

-----Original Message-----

**Comment by tmyroadctfig** [comment]
Hi Shrikant,

sivaktamilan is correct, the licence file has details about the terms.


Cheers,

Luke
